Configure Application Gateway custom probe (#206)
This commit configures a custom probe for Application Gateway.
Custom probes now support status codes other than 200-399, so
configure the probe to also consider a 401 response as healthy.
This removes the need to configure anonymous access to the cluster
base path.

Looked at condesing both gateway resources into one, but Application Gateway validation does not allow an empty object for webApplicationFirewallConfiguration; it fails validation with

error: ApplicationGatewayFirewallCannotBeEnabledForSelectedSku : Application Gateway /subscriptions/<subscription id>/resourceGroups/<resource group>/providers/Microsoft.Network/applicationGateways/es-app-gateway does not support WebApplicationFirewall with the selected SKU tier Standard

Closes #201