Set path.data for non-data nodes
When unspecified, Elasticsearch 6.x will attempt to write data to /usr/share/elasticsearch/data which
the elasticsearch user under which the service runs does not have access to.

This can be seen in the elasticsearch.log as similar to

[2018-02-13T05:19:08,503][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalStateException: Unable to access 'path.data' (/usr/share/elasticsearch/data)
        at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:307) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:262) ~[elasticsearch-6.2.1.jar:6.2.1]
        ...